kind: ConfigMap
apiVersion: v1
metadata:
  name: yasumipuzzleboxcalculator
  labels:
    karaf.pid: com.rhworkshop.msa.yasumipuzzleboxcalculator

data:
  Puzzler.Start.Destination: qa.test.yasumi.start
  Puzzler.Stop.Destination: qa.test.yasumi.stop
  Puzzler.PuzzleBox.Destination: qa.test.yasumi.puzzlebox.start
  Puzzler.Forward.Destination: qa.test.yasumi.forwardEntry
  Puzzler.Solution.Destination: qa.test.yasumi.solutionEntry
  Puzzler.amq.BrokerURL: tcp://TODO_SPECIFY_IP:61616
  Puzzler.amq.Username: admin
  Puzzler.amq.Password: admin
  Puzzler.TestMessage: QA PUZZLER TESTING
  Puzzler.Process.Tuning.SplitLevel: "3"
  Puzzler.Process.Tuning.BucketSize: "200"
  Puzzler.Process.Tuning.ComputeLevel: "3"
  Puzzler.Process.Tuning.StopLevele: "5"
  Puzzler.amq.tuning.maxConnections: "2"
  Puzzler.amq.tuning.maximumActiveSessionPerConnectione: "50"
  Puzzler.amq.tuning.concurrentConsumers: "2"